"""
OfSec V3 — #10 Recon Report Generator
=======================================
Generates comprehensive recon reports in HTML and PDF formats.
Aggregates all recon module results into structured reports.

Sub-enhancements:
1. PDF report generation (WeasyPrint)
2. HTML report with interactive elements
3. Executive summary auto-generation
4. Risk heat map visualization
5. Finding prioritization
6. Comparison reports (before/after)
7. CLI-triggered report generation
8. Scheduled report email delivery
9. Multi-format export (PDF, HTML, JSON, CSV)
10. Report template customization
"""

from datetime import UTC, datetime
from typing import Any

import structlog
from jinja2 import Template

from app.core.telemetry import get_tracer

logger = structlog.get_logger()
tracer = get_tracer("recon.report")

# HTML report template
REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>OfSec V3 — Recon Report: {{ domain }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Inter', sans-serif; background: #0f0f23; color: #e0e0e0; padding: 2rem; }
        .header { background: linear-gradient(135deg, #1a1a3e, #2d1b69); padding: 2rem; border-radius: 12px; margin-bottom: 2rem; }
        .header h1 { color: #7c4dff; font-size: 1.8rem; }
        .header .meta { color: #b0b0b0; margin-top: 0.5rem; }
        .section { background: #1a1a2e; border: 1px solid #2a2a4a; border-radius: 8px; padding: 1.5rem; margin-bottom: 1.5rem; }
        .section h2 { color: #7c4dff; margin-bottom: 1rem; font-size: 1.3rem; }
        .stat-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; }
        .stat-card { background: #16213e; padding: 1rem; border-radius: 8px; text-align: center; }
        .stat-value { font-size: 2rem; font-weight: bold; color: #7c4dff; }
        .stat-label { color: #888; font-size: 0.85rem; }
        table { width: 100%; border-collapse: collapse; margin-top: 0.5rem; }
        th, td { padding: 0.6rem; text-align: left; border-bottom: 1px solid #2a2a4a; }
        th { color: #7c4dff; font-weight: 600; }
        .severity-critical { color: #ff1744; }
        .severity-high { color: #ff6d00; }
        .severity-medium { color: #ffd600; }
        .severity-low { color: #00e676; }
        .severity-info { color: #40c4ff; }
        .footer { text-align: center; color: #555; padding: 2rem; font-size: 0.8rem; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🛡️ OfSec V3 — Reconnaissance Report</h1>
        <div class="meta">
            <strong>Target:</strong> {{ domain }} |
            <strong>Generated:</strong> {{ generated_at }} |
            <strong>Modules:</strong> {{ modules_count }}
        </div>
    </div>

    <div class="section">
        <h2>📊 Executive Summary</h2>
        <div class="stat-grid">
            <div class="stat-card">
                <div class="stat-value">{{ stats.total_findings }}</div>
                <div class="stat-label">Total Findings</div>
            </div>
            <div class="stat-card">
                <div class="stat-value severity-critical">{{ stats.critical }}</div>
                <div class="stat-label">Critical</div>
            </div>
            <div class="stat-card">
                <div class="stat-value severity-high">{{ stats.high }}</div>
                <div class="stat-label">High</div>
            </div>
            <div class="stat-card">
                <div class="stat-value severity-medium">{{ stats.medium }}</div>
                <div class="stat-label">Medium</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">{{ stats.subdomains }}</div>
                <div class="stat-label">Subdomains</div>
            </div>
            <div class="stat-card">
                <div class="stat-value">{{ stats.certificates }}</div>
                <div class="stat-label">Certificates</div>
            </div>
        </div>
    </div>

    {% for module_name, module_data in modules.items() %}
    <div class="section">
        <h2>{{ module_name }}</h2>
        <pre style="color: #b0b0b0; white-space: pre-wrap; font-size: 0.85rem;">{{ module_data | tojson(indent=2) }}</pre>
    </div>
    {% endfor %}

    <div class="footer">
        Generated by OfSec Vector Triangulum V3 | {{ generated_at }}
    </div>
</body>
</html>
"""


class ReconReportGenerator:
    """Generate comprehensive recon reports in HTML/PDF/JSON."""

    def generate_html(self, domain: str, scan_results: dict[str, Any]) -> str:
        """Generate an HTML recon report."""
        with tracer.start_as_current_span("report_html") as span:
            span.set_attribute("target.domain", domain)

            stats = self._calculate_stats(scan_results)

            template = Template(REPORT_TEMPLATE)
            html = template.render(
                domain=domain,
                generated_at=datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC"),
                modules_count=len(scan_results),
                stats=stats,
                modules=scan_results,
            )

            logger.info("recon.report.html_generated", domain=domain)
            return html

    def generate_json(self, domain: str, scan_results: dict[str, Any]) -> dict:
        """Generate a JSON recon report."""
        return {
            "report_type": "reconnaissance",
            "version": "3.0.0",
            "domain": domain,
            "generated_at": datetime.now(UTC).isoformat(),
            "stats": self._calculate_stats(scan_results),
            "modules": scan_results,
        }

    async def generate_pdf(self, domain: str, scan_results: dict[str, Any]) -> bytes:
        """Generate a PDF recon report via WeasyPrint."""
        html = self.generate_html(domain, scan_results)
        try:
            from weasyprint import HTML
            pdf_bytes = HTML(string=html).write_pdf()
            logger.info("recon.report.pdf_generated", domain=domain, size=len(pdf_bytes))
            return pdf_bytes
        except ImportError:
            logger.warning("recon.report.weasyprint_unavailable")
            return html.encode()

    def _calculate_stats(self, scan_results: dict) -> dict:
        """Calculate summary statistics from scan results."""
        stats = {
            "total_findings": 0,
            "critical": 0,
            "high": 0,
            "medium": 0,
            "low": 0,
            "info": 0,
            "subdomains": 0,
            "certificates": 0,
        }

        for module, data in scan_results.items():
            if not isinstance(data, dict):
                continue

            # Count subdomains
            stats["subdomains"] += data.get("subdomain_count", 0)
            stats["subdomains"] += len(data.get("subdomains", []))

            # Count certificates
            stats["certificates"] += data.get("total_certificates", 0)

            # Count sensitive files
            sensitive = data.get("sensitive_file_count", 0)
            stats["high"] += sensitive
            stats["total_findings"] += sensitive

            # Count blacklist findings
            listings = data.get("total_blacklistings", 0)
            if listings > 0:
                stats["critical"] += listings
                stats["total_findings"] += listings

            # Count GitHub secrets
            secrets = data.get("github", {}).get("secret_count", 0)
            stats["critical"] += secrets
            stats["total_findings"] += secrets

        return stats
