"""initial_schema

Revision ID: c9ca0cb61324
Revises: 
Create Date: 2026-03-05 10:36:04.648534
"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c9ca0cb61324'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
